[[constraint]]
	name = "github.com/urfave/cli"
	version = "1.19.1"

[[constraint]]
    name = "github.com/influxdata/go-syslog"
    version = "2.0.0"

[[constraint]]
    name = "golang.org/x/sync"
    branch = "master"

[[constraint]]
    name = "gopkg.in/mcuadros/go-syslog.v2"
    version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
