[[constraint]]
	name = "github.com/urfave/cli"
	version = "1.19.1"

[[constraint]]
    name = "github.com/influxdata/go-syslog"
    version = "2.0.0"

[[constraint]]
    name = "golang.org/x/sync"
    branch = "master"

[[constraint]]
    name = "gopkg.in/mcuadros/go-syslog.v2"
    version = "2.2.1"

[[constraint]]
    name = "github.com/nsqio/nsq"
    version = "1.1.0"

[[constraint]]
    name = "github.com/inconshreveable/log15"
    version = "2.14"

[[constraint]]
    name = "github.com/oklog/ulid"
    version = "1.3.1"

[[constraint]]
    name = "github.com/go-redis/redis"
    version = "6.15.1"

[[constraint]]
    name = "github.com/Shopify/sarama"
    version = "1.20.1"

[prune]
  go-tests = true
  unused-packages = true
