[[constraint]]
	name = "github.com/urfave/cli"
	version = "1.19.1"

[[constraint]]
    name = "github.com/influxdata/go-syslog"
    version = "2.0.0"

[[constraint]]
    name = "golang.org/x/sync"
    branch = "master"

[[constraint]]
    name = "github.com/nsqio/nsq"
    version = "1.1.0"

[[constraint]]
    name = "github.com/inconshreveable/log15"
    version = "2.14"

[[constraint]]
    name = "github.com/oklog/ulid"
    version = "1.3.1"

[[constraint]]
    name = "github.com/go-redis/redis"
    version = "6.15.1"

[[constraint]]
    name = "github.com/Shopify/sarama"
    version = "1.20.1"

[[constraint]]
    name = "github.com/olivere/elastic"
    version = "6.2.15"

[[constraint]]
    name = "github.com/orcaman/concurrent-map"
    branch = "master"

[[constraint]]
    name = "github.com/gorilla/websocket"
    version = "1.4.0"

[[constraint]]
    name = "github.com/gin-gonic/gin"
    version = "1.3.0"

[[constraint]]
    name = "github.com/tinylib/msgp"
    version = "1.1.0"

[[constraint]]
    name = "go.uber.org/atomic"
    version = "1.3.2"

[[constraint]]
    name = "github.com/streadway/amqp"
    branch = "master"

[[constraint]]
    name = "github.com/prometheus/client_golang"
    version = "0.9.2"

[prune]
  go-tests = true
  unused-packages = true
